version: '2'

services:
    elasticsearch:
        build: elasticsearch/
        environment: 
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        ports: 
            - "9200:9200"
            - "9300:9300"
        networks:
            - docker_ek
    kibana:
        build: kibana/
        ports: 
            - "5601:5601"
        networks:
            - docker_ek
        depends_on:
            - elasticsearch
    drupal:
        image: drupal:8.2-apache
#        build: drupal/
        ports:
            - "8080:80"
        volumes: 
            ## This must be the code folder for Drupal 8.2.6
            - ./code/drupal:/var/www/html
        links:  
            - mysql:mysql
        networks:
            - docker_ek
        restart: always
    mysql:
        image: mariadb:10
        environment:
            MYSQL_USER: drupal
            MYSQL_PASSWORD: drupal
            MYSQL_DATABASE: drupal
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3306:3306"
        volumes: 
            - ./data/mysql:/var/lib/mysql
        networks:
            - docker_ek
        restart: always

networks:
    docker_ek:
        driver: bridge